# SPDX-FileCopyrightText: 2025 STRATO GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Shell Script Configuration Check

on:
    pull_request:

permissions:
    contents: read

concurrency:
    group: shell-script-config-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
  check-config-system-set:
    runs-on: ubuntu-latest
    name: Check for config:system:set usage in shell scripts

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Check for config:system:set usage
      run: |
        ./.github/check-shell-config.sh
